spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 10000          # 10s – close idle connections fairly quickly
      max-lifetime: 30000          # 30s – recycle before Railway drops them
      connection-timeout: 10000    # 10s – don't hang forever
      validation-timeout: 5000     # 5s – quick fail for bad connections
      leak-detection-threshold: 20000  # 20s – log if a connection is “stuck”

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

  redis:
    host: ${REDISHOST}
    port: ${REDISPORT}
    password: ${REDISPASSWORD}
    ssl: false  # # internal Railway Redis uses plain TCP.

  graphql:
    graphiql:
      enabled: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 900000       # 15 min
  refresh-expiration-ms: 604800000 # 7 days

queue:
  main-exec-worker-count: 5
  sched-exec-worker-count: 2

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    enable:
      jvm: false
      process: false
      system: false
      executor: false
      hibernate: false
      logback: false
