spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springqpro
    username: springqpro
    password: springqpro
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0

# Redis cache defaults for my Task entities.
cache:
  task:
    ttl-seconds: 600  # 10 minutes

graphql:
  graphiql:
    enabled: true  # enable in-browser GraphiQL UI
  schema:
    locations: classpath:graphql/

jwt:
  secret: "CHANGEME_SUPER_SECRET_256_BIT_VALUE"
  expirationMs: 86400000   # 24 hours